# this is a java project using maven
# it also compiles an android result with gradle
# see https://github.com/travis-ci/travis-ci/issues/2551
language: java
# 
# Java 8
#  
# to avoid Unsupported major.minor version 52.0 we need to specify the JDK to be used
# https://stackoverflow.com/a/40208648/1497139
jdk: oraclejdk8
# support for headless Swing tests and other gui stuff
# https://docs.travis-ci.com/user/gui-and-headless-browsers/ 
# workaround 2017-08-06
dist: precise
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
# proposed xvfb fix
#before_install: sudo apt-get install xvfb firefox
# switch off gpg handling
install: mvn install -DskipTests=true -Dgpg.skip=true
script: mvn test

# Java FX support
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
