# 2017-08-20 - initial configuration for javafx
# workaround 2017-08-20
# xvfb support
dist: precise
# this is a java project using maven
language: java
jdk:
  - oraclejdk8
# GUI initialization
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
# switch off gpg handling
install: mvn install -Dgpg.skip=true
# Java FX support
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
