# this is a java project using maven
# it also compiles an android result with gradle
# see https://github.com/travis-ci/travis-ci/issues/2551
language: java
# 
# Java 8
#  
# to avoid Unsupported major.minor version 52.0 we need to specify the JDK to be used
# https://stackoverflow.com/a/40208648/1497139
jdk: oraclejdk8
# support for headless Swing tests and other gui stuff
# https://docs.travis-ci.com/user/gui-and-headless-browsers/ 
# workaround 2017-08-06
#dist: precise
#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start
# proposed xvfb fix
env:
  global:
    - DISPLAY=:99

before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - sleep 3
sudo: required 
before_install: sudo apt-get install xvfb
# switch off gpg handling
install: mvn install -DskipTests=true -Dgpg.skip=true
script: mvn test

# Java FX support
addons:
  apt:
    packages:
      - oracle-java8-installer
