# 2017-08-20 - initial configuration for javafx
# workaround 2017-08-20
# this is a java project using maven
language: java
jdk:
  - oraclejdk8
# GUI initialization
# see https://github.com/travis-ci/travis-ci/issues/8262#issue-251064430
env:
  global:
    - DISPLAY=:99

before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - sleep 3
# switch off gpg handling
install: mvn install -Dgpg.skip=true
# Java FX support
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
